import Foundation

/// Whether the content a lookup occurred on was authored / imported by the user
/// or generated by AI (LM02-S4a). v1 is always `.userAuthored` — reading
/// documents are always user-imported, and there is no path turning AI-generated
/// learning text into a reading document. `.aiGenerated` is a **forward schema
/// seam** for a future "learning material as reading source" capability, where a
/// second-order closure (level → generated text → lookups → band) would need
/// guarding (the filtering decision belongs to S4b).
public enum SourceContentOrigin: String, Codable, CaseIterable, Equatable, Sendable {
    case userAuthored
    case aiGenerated
}

/// A captured "looked up a word / requested an explanation" behaviour event
/// (LM02-S4a). A **user behaviour signal**, not an AI judgement: it records that
/// the user asked for an explanation of some text at some time — never the AI's
/// returned explanation or any AI-assigned difficulty.
///
/// An unrecomputable user-behaviour signal: persisted local-only, excluded from
/// backup and export (a single lookup is low value, and band re-estimation can
/// gracefully degrade from the remaining signals).
public struct DictionaryLookupEvent: Sendable, Equatable, Identifiable {
    public let id: String
    public let languageSpaceID: String
    public let lookedUpTerm: String
    /// The reading document / source the lookup occurred on (nullable weak ref).
    public let sourceContentID: String?
    public let sourceContentOrigin: SourceContentOrigin
    public let occurredAt: Date
    public let softDeletedAt: Date?

    public init(
        id: String,
        languageSpaceID: String,
        lookedUpTerm: String,
        sourceContentID: String?,
        sourceContentOrigin: SourceContentOrigin = .userAuthored,
        occurredAt: Date,
        softDeletedAt: Date? = nil
    ) {
        self.id = id
        self.languageSpaceID = languageSpaceID
        self.lookedUpTerm = lookedUpTerm
        self.sourceContentID = sourceContentID
        self.sourceContentOrigin = sourceContentOrigin
        self.occurredAt = occurredAt
        self.softDeletedAt = softDeletedAt
    }
}
