import Foundation

/// The rolling conversation summary for a companion thread (LM03-S3b-1 "对话记忆").
///
/// When a single companion conversation grows past the context window, the turns
/// that age out of the recent-verbatim window are folded into this summary and
/// injected as a delimited reference block, so the companion stays grounded in
/// "what we talked about earlier" without re-sending the whole transcript.
///
/// **Derived / recomputable**: it is a cache over `companion_messages`, never a
/// source of truth — it can always be regenerated by re-summarizing the messages.
/// `coversThroughSequence` is the watermark: the summary folds every message with
/// `sequence <= coversThroughSequence`. That watermark is what makes the
/// delete-and-after invalidation rule decidable (idea-03 §3.2): deleting a message
/// at or before the watermark means the summary covers now-deleted content and
/// must be invalidated + rebuilt, otherwise the deleted content keeps influencing
/// replies through the stale summary.
///
/// **Privacy / persistence**: only summarizes this conversation's own messages
/// (never Memory life facts / records / band signals); local-only, not synced;
/// rides the thread row's backup/export lane as a regenerable cache column.
public struct CompanionRollingSummary: Codable, Equatable, Sendable {
    /// The summary text injected as the `<<<CONVERSATION MEMORY>>>` reference block.
    public var text: String
    /// Watermark: the summary folds every message with `sequence <= this value`.
    public var coversThroughSequence: Int
    public var updatedAt: Date

    public init(text: String, coversThroughSequence: Int, updatedAt: Date) {
        self.text = text
        self.coversThroughSequence = coversThroughSequence
        self.updatedAt = updatedAt
    }
}
